//! REALITY.2 Task 7: the `connect()` orchestration and `RealityStream`
//! application-data stream.
//!
//! Composes [`crate::hello`], [`crate::auth`], and [`crate::handshake`] into
//! a full RFC 8446 §2 one-round-trip TLS 1.3 client handshake carrying a
//! REALITY auth seal in the `ClientHello`'s `legacy_session_id`, then hands
//! back an `AsyncRead + AsyncWrite` stream over the negotiated application
//! traffic keys. REALITY is zero-cert-auth by design (the whole point is
//! that the wire is indistinguishable from a real TLS 1.3 connection to the
//! camouflage SNI): this module does not verify the server's certificate
//! chain or the server's `CertificateVerify`/`Finished` contents, but it
//! does consume every handshake message so the transcript stays correct.
//!
//! The ephemeral X25519 key is generated once, as raw bytes, and reused for
//! both the TLS `key_share`/ECDHE *and* the REALITY auth seal's ECDH — see
//! [`connect`]'s first few lines. `ring::agreement` cannot be used for this
//! because its private key is not extractable, so the same key could not
//! also seal the REALITY auth payload.

use crate::auth;
use crate::error::Error;
use crate::handshake::{
    self, derive_application_keys, derive_handshake_keys, finished_verify_data, parse_server_hello,
    record_open, record_open_typed, record_seal, transcript_hash, HandshakeKeys, GROUP_X25519,
    GROUP_X25519MLKEM768,
};
use crate::hello::{self, ClientHelloParams, RandomSource};
use ml_kem::kem::Decapsulate;
use ml_kem::{EncodedSizeUser, KemCore, MlKem768};
use std::io;
use std::pin::Pin;
use std::task::{Context, Poll};
use std::time::{SystemTime, UNIX_EPOCH};
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt, ReadBuf};

/// Byte length of an ML-KEM-768 ciphertext (FIPS 203 §7.2) — the length of
/// the leading portion of a group-`4588` server `key_share`.
const MLKEM768_CIPHERTEXT_LEN: usize = 1088;

/// TLS record-layer content types (RFC 8446 §5.1).
const CONTENT_TYPE_CHANGE_CIPHER_SPEC: u8 = 0x14;
const CONTENT_TYPE_ALERT: u8 = 0x15;
const CONTENT_TYPE_HANDSHAKE: u8 = 0x16;
const CONTENT_TYPE_APPLICATION_DATA: u8 = 0x17;

/// `AlertDescription::close_notify` (RFC 8446 §6.1) — the one alert a
/// well-behaved peer sends to end a connection cleanly; every other alert
/// description is a genuine error.
const ALERT_DESCRIPTION_CLOSE_NOTIFY: u8 = 0;

/// Handshake message type for `Finished` (RFC 8446 §4.4.4).
const HS_TYPE_FINISHED: u8 = 0x14;

/// `record_header ‖ payload` header size: `type(1) ‖ legacy_version(2) ‖
/// length(2)`.
const RECORD_HEADER_LEN: usize = 5;

/// The `legacy_record_version` BoringSSL/Chrome (and this crate's crafted
/// `ClientHello`) put on the very first record. Ignored by any TLS 1.3-aware
/// receiver, but matched for byte-fidelity.
const LEGACY_RECORD_VERSION_INITIAL: u16 = 0x0301;
/// The `legacy_record_version` used on every record after the first
/// (RFC 8446 §5.1: "MUST be set to 0x0303 for all records generated by a
/// TLS 1.3 implementation other than an initial ClientHello").
const LEGACY_RECORD_VERSION: u16 = 0x0303;

/// A `ChangeCipherSpec` record, sent by the client for middlebox-compatibility
/// (RFC 8446 §D.4) immediately before the encrypted client `Finished`,
/// matching what real Chrome/BoringSSL sends.
const CHANGE_CIPHER_SPEC_RECORD: [u8; 6] = [
    CONTENT_TYPE_CHANGE_CIPHER_SPEC,
    0x03,
    0x03,
    0x00,
    0x01,
    0x01,
];

/// The largest single TLS record plaintext RFC 8446 §5.1 permits.
const MAX_APP_RECORD_LEN: usize = 16384;

/// A generous sanity bound on a single handshake *message* (not record)
/// length while scanning the server's unauthenticated-length-prefixed
/// handshake flight for `Finished` — well above any real
/// EncryptedExtensions/Certificate/CertificateVerify/Finished flight, but
/// far below "attacker can make us buffer gigabytes" territory.
const MAX_HANDSHAKE_MSG_LEN: usize = 1 << 20;

/// Upper bound on the TOTAL decrypted server handshake flight
/// (EncryptedExtensions + Certificate + CertificateVerify + Finished). A real
/// flight is tens of KiB; 256 KiB is generous. Without this, a peer (the outer
/// TLS is zero-server-auth, so this could be a MITM) can stream endless valid
/// non-`Finished` handshake messages and exhaust our memory (review I1).
const MAX_SERVER_FLIGHT_LEN: usize = 256 * 1024;

/// [`RandomSource`] backed by the OS CSPRNG (`getrandom`), for driving
/// [`hello::craft`] in production. [`RandomSource::fill`] cannot itself
/// return a `Result`, so failures are latched and surfaced by
/// [`OsRng::into_result`] after `craft` returns — `craft` only ever
/// transforms already-filled bytes, so a latched failure part-way through
/// still produces *some* `Vec<u8>` (built from bytes that silently stayed
/// zero once RNG failed), but [`connect`] discards it and bails out via
/// `into_result` before ever putting it on the wire.
#[derive(Default)]
struct OsRng {
    error: Option<getrandom::Error>,
}

impl OsRng {
    fn into_result(self) -> Result<(), Error> {
        match self.error {
            Some(e) => Err(Error::Rng(e)),
            None => Ok(()),
        }
    }
}

impl RandomSource for OsRng {
    fn fill(&mut self, buf: &mut [u8]) {
        if self.error.is_some() {
            return;
        }
        if let Err(e) = getrandom::getrandom(buf) {
            self.error = Some(e);
        }
    }
}

/// The same OS-CSPRNG-backed, latched-error `getrandom` bridge as [`OsRng`],
/// but implementing `rand_core::{RngCore, CryptoRng}` instead of
/// [`RandomSource`] — the trait bound `ml_kem::MlKem768::generate` needs
/// (`rand_core::CryptoRngCore`, blanket-implemented for any
/// `RngCore + CryptoRng`). `rand_core::RngCore::fill_bytes` has no `Result`
/// return, so a `getrandom` failure is latched the same way `OsRng` latches
/// one, and [`MlKemRng::into_result`] surfaces it to the caller after
/// `generate` returns (which, on a latched failure, still returns *some*
/// keypair built from bytes that silently stayed zero — [`connect`] discards
/// it and bails out via `into_result` before ever using it).
#[derive(Default)]
struct MlKemRng {
    error: Option<getrandom::Error>,
}

impl MlKemRng {
    fn into_result(self) -> Result<(), Error> {
        match self.error {
            Some(e) => Err(Error::Rng(e)),
            None => Ok(()),
        }
    }
}

impl rand_core::RngCore for MlKemRng {
    fn next_u32(&mut self) -> u32 {
        let mut buf = [0u8; 4];
        self.fill_bytes(&mut buf);
        u32::from_ne_bytes(buf)
    }

    fn next_u64(&mut self) -> u64 {
        let mut buf = [0u8; 8];
        self.fill_bytes(&mut buf);
        u64::from_ne_bytes(buf)
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        if self.error.is_some() {
            return;
        }
        if let Err(e) = getrandom::getrandom(dest) {
            self.error = Some(e);
        }
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core::Error> {
        self.fill_bytes(dest);
        Ok(())
    }
}

impl rand_core::CryptoRng for MlKemRng {}

/// Builds a 5-byte TLS record header for a `content_type`/`legacy_version`
/// record of plaintext-or-ciphertext length `len`.
fn record_header(
    content_type: u8,
    version: u16,
    len: usize,
) -> Result<[u8; RECORD_HEADER_LEN], Error> {
    let len_u16 = u16::try_from(len).map_err(|_| Error::Protocol("record length exceeds a u16"))?;
    let v = version.to_be_bytes();
    let l = len_u16.to_be_bytes();
    Ok([content_type, v[0], v[1], l[0], l[1]])
}

/// Reads one raw TLS record (5-byte header + body) off `stream`. Returns the
/// outer record type and the (still possibly-encrypted) body.
async fn read_raw_record<S: AsyncRead + Unpin>(stream: &mut S) -> Result<(u8, Vec<u8>), Error> {
    let mut header = [0u8; RECORD_HEADER_LEN];
    stream.read_exact(&mut header).await?;
    let len = usize::from(u16::from_be_bytes([header[3], header[4]]));
    let mut payload = vec![0u8; len];
    stream.read_exact(&mut payload).await?;
    Ok((header[0], payload))
}

/// Scans `hs_flight` (the concatenation of every handshake message decrypted
/// so far from the server's post-`ServerHello` flight) for a complete
/// `Finished` message. Returns the byte offset one past the end of that
/// message on success, or `Ok(None)` if the flight so far ends mid-message
/// (caller should decrypt and append another record and retry).
fn find_finished_end(hs_flight: &[u8]) -> Result<Option<usize>, Error> {
    let mut pos = 0;
    while hs_flight.len() >= pos + 4 {
        let msg_type = hs_flight[pos];
        let len = (usize::from(hs_flight[pos + 1]) << 16)
            | (usize::from(hs_flight[pos + 2]) << 8)
            | usize::from(hs_flight[pos + 3]);
        if len > MAX_HANDSHAKE_MSG_LEN {
            return Err(Error::Protocol(
                "server handshake message exceeds sane length bound",
            ));
        }
        let msg_end = pos + 4 + len;
        if hs_flight.len() < msg_end {
            break;
        }
        if msg_type == HS_TYPE_FINISHED {
            return Ok(Some(msg_end));
        }
        pos = msg_end;
    }
    Ok(None)
}

/// Performs a full RFC 8446 §2 one-round-trip TLS 1.3 client handshake to
/// `stream`, carrying a REALITY auth seal (keyed by `server_reality_pub` and
/// `short_id`) in the crafted Chrome-150 `ClientHello`'s `legacy_session_id`.
/// On success, returns a [`RealityStream`] over the negotiated application
/// traffic keys.
///
/// Does not verify the server's certificate chain, `CertificateVerify`, or
/// `Finished` contents — REALITY's camouflage design means the server on the
/// other end of a *successful* connection presents the real target site's
/// certificate, which this client has no way (and no need) to validate; a
/// misconfigured or non-REALITY-aware peer simply fails to open the auth
/// seal server-side and this handshake either times out or is rejected
/// upstream, not here.
pub async fn connect<S: AsyncRead + AsyncWrite + Unpin>(
    mut stream: S,
    sni: &str,
    server_reality_pub: &[u8; 32],
    short_id: [u8; 8],
) -> Result<RealityStream<S>, Error> {
    // THE ONE EPHEMERAL KEY: raw bytes from getrandom, reused via
    // x25519-dalek for both the TLS key_share/ECDHE and the REALITY auth
    // seal's ECDH. Never ring::agreement — its private key isn't
    // extractable, so it could not be reused for the seal.
    let mut eph_priv = [0u8; 32];
    getrandom::getrandom(&mut eph_priv)?;
    let secret = x25519_dalek::StaticSecret::from(eph_priv);
    let eph_pub: [u8; 32] = x25519_dalek::PublicKey::from(&secret).to_bytes();

    // A genuine ML-KEM-768 keypair (REALITY.2 Task 9), generated fresh per
    // connection like the X25519 ephemeral key above. Real Chrome sends
    // `X25519MLKEM768` (group 4588) as its PRIMARY key_share, and real
    // ML-KEM-strict servers (Cloudflare, Google) validate the encapsulation
    // key's canonical encoding — only a genuine key survives that check (see
    // `hello::key_share_body`'s doc comment). `mlkem_dk` is kept to complete
    // the hybrid exchange if the server selects group 4588 below; `mlkem_ek`
    // is sent as-is in the ClientHello.
    let mut mlkem_rng = MlKemRng::default();
    let (mlkem_dk, mlkem_ek) = MlKem768::generate(&mut mlkem_rng);
    mlkem_rng.into_result()?;

    let mut client_random = [0u8; 32];
    getrandom::getrandom(&mut client_random)?;

    let ts_min = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|_| Error::Clock)?
        .as_secs()
        / 60;

    let legacy_session_id = auth::seal(
        server_reality_pub,
        &eph_priv,
        &client_random,
        short_id,
        ts_min,
    );

    let params = ClientHelloParams {
        sni: sni.to_string(),
        key_share_x25519_pub: eph_pub,
        key_share_mlkem_ek: mlkem_ek.as_bytes().to_vec(),
        legacy_session_id,
        client_random,
    };
    let mut rng = OsRng::default();
    let hello_msg = hello::craft(&params, &mut rng);
    rng.into_result()?;

    let ch_header = record_header(
        CONTENT_TYPE_HANDSHAKE,
        LEGACY_RECORD_VERSION_INITIAL,
        hello_msg.len(),
    )?;
    stream.write_all(&ch_header).await?;
    stream.write_all(&hello_msg).await?;

    // ServerHello is sent plaintext (record type 0x16) — RFC 8446 §5.1.
    let (record_type, sh_msg) = read_raw_record(&mut stream).await?;
    if record_type != CONTENT_TYPE_HANDSHAKE {
        return Err(Error::Protocol(
            "expected a plaintext ServerHello handshake record",
        ));
    }
    let server_hello_info = parse_server_hello(&sh_msg)?;

    let mut ch_sh_transcript = Vec::with_capacity(hello_msg.len() + sh_msg.len());
    ch_sh_transcript.extend_from_slice(&hello_msg);
    ch_sh_transcript.extend_from_slice(&sh_msg);
    let transcript_ch_sh = transcript_hash(&ch_sh_transcript, server_hello_info.suite);

    // The (possibly hybrid) ECDHE shared secret fed to the TLS 1.3 key
    // schedule (RFC 8446 §7.1's "(EC)DHE" input, generalized to `&[u8]` —
    // see `derive_handshake_keys`'s doc comment). Group 29 (plain X25519):
    // 32 bytes, the X25519 ECDH output alone. Group 4588
    // (X25519MLKEM768): 64 bytes, `mlkem_shared_secret(32) ‖
    // x25519_shared_secret(32)` — ML-KEM first, matching the client
    // `key_share` entry's own `mlkem_ek ‖ x25519_pub` byte order (see
    // `hello::key_share_body`), per
    // draft-kwiatkowski-tls-ecdhe-mlkem's hybrid combiner. The server's
    // group-4588 key_share is `mlkem768_ciphertext(1088) ‖
    // x25519_public(32)` — `parse_server_hello` already validated that
    // exact length for this group.
    let ecdhe: Vec<u8> = match server_hello_info.group {
        GROUP_X25519MLKEM768 => {
            let (ct_bytes, server_x25519_pub) = server_hello_info
                .server_key_share
                .split_at(MLKEM768_CIPHERTEXT_LEN);
            let ciphertext = ct_bytes
                .try_into()
                .map_err(|_| handshake::Error::MlKemDecapsulation)?;
            let mlkem_ss = mlkem_dk
                .decapsulate(&ciphertext)
                .map_err(|()| handshake::Error::MlKemDecapsulation)?;
            let server_x25519_pub: [u8; 32] = server_x25519_pub
                .try_into()
                .map_err(|_| handshake::Error::BadKeyShareLength)?;
            let x25519_ss = secret
                .diffie_hellman(&x25519_dalek::PublicKey::from(server_x25519_pub))
                .to_bytes();

            let mut combined = Vec::with_capacity(64);
            combined.extend_from_slice(&mlkem_ss);
            combined.extend_from_slice(&x25519_ss);
            combined
        }
        GROUP_X25519 => {
            let server_x25519_pub: [u8; 32] = server_hello_info
                .server_key_share
                .as_slice()
                .try_into()
                .map_err(|_| handshake::Error::BadKeyShareLength)?;
            secret
                .diffie_hellman(&x25519_dalek::PublicKey::from(server_x25519_pub))
                .to_bytes()
                .to_vec()
        }
        _ => {
            return Err(Error::Protocol(
                "parse_server_hello returned an unexpected key_share group",
            ))
        }
    };
    let hk: HandshakeKeys =
        derive_handshake_keys(&ecdhe, &transcript_ch_sh, server_hello_info.suite);

    // Read the server's EncryptedExtensions/Certificate/CertificateVerify/
    // Finished flight: one or more 0x17 records under the server handshake
    // traffic key, possibly preceded by a middlebox-compatibility CCS.
    let mut hs_flight = Vec::new();
    let mut server_seq = 0u64;
    let finished_end = loop {
        let (record_type, mut payload) = read_raw_record(&mut stream).await?;
        if record_type == CONTENT_TYPE_CHANGE_CIPHER_SPEC {
            continue;
        }
        if record_type != CONTENT_TYPE_APPLICATION_DATA {
            return Err(Error::Protocol(
                "expected an encrypted handshake record in the server flight",
            ));
        }
        let opened = record_open(
            &hk.server_key,
            &hk.server_iv,
            server_seq,
            server_hello_info.suite,
            record_type,
            &mut payload,
        )?;
        server_seq = server_seq
            .checked_add(1)
            .ok_or(Error::Protocol("server handshake sequence overflow"))?;
        hs_flight.extend_from_slice(&opened);
        if hs_flight.len() > MAX_SERVER_FLIGHT_LEN {
            return Err(Error::Protocol(
                "server handshake flight exceeds sane bound",
            ));
        }

        if let Some(end) = find_finished_end(&hs_flight)? {
            break end;
        }
    };
    hs_flight.truncate(finished_end);

    let mut full_transcript = ch_sh_transcript;
    full_transcript.extend_from_slice(&hs_flight);
    let transcript_thru_sfin = transcript_hash(&full_transcript, server_hello_info.suite);

    // Client Finished: verify_data = HMAC-Hash(finished_key, transcript),
    // finished_key = HKDF-Expand-Label(client_hs_traffic, "finished", "",
    // Hash.length) — Hash is the suite's key-schedule hash throughout (RFC
    // 8446 §4.4.4/§7.1), so verify_data is 32 bytes for SHA-256-hash suites
    // but 48 bytes for TLS_AES_256_GCM_SHA384 (0x1302); the u24 length
    // prefix below must match that, not be hardcoded.
    let verify_data = finished_verify_data(
        &hk.client_hs_traffic,
        &transcript_thru_sfin,
        server_hello_info.suite,
    );

    let mut client_finished_msg = Vec::with_capacity(4 + verify_data.len());
    client_finished_msg.push(HS_TYPE_FINISHED);
    let vd_len = u32::try_from(verify_data.len())
        .map_err(|_| Error::Protocol("Finished verify_data length exceeds a u24"))?;
    client_finished_msg.extend_from_slice(&vd_len.to_be_bytes()[1..]); // u24
    client_finished_msg.extend_from_slice(&verify_data);

    // Middlebox-compatibility CCS, then the sealed client Finished, matching
    // real Chrome/BoringSSL's wire shape.
    stream.write_all(&CHANGE_CIPHER_SPEC_RECORD).await?;

    let sealed_finished = record_seal(
        &hk.client_key,
        &hk.client_iv,
        0,
        server_hello_info.suite,
        CONTENT_TYPE_HANDSHAKE,
        &client_finished_msg,
    )?;
    let fin_header = record_header(
        CONTENT_TYPE_APPLICATION_DATA,
        LEGACY_RECORD_VERSION,
        sealed_finished.len(),
    )?;
    stream.write_all(&fin_header).await?;
    stream.write_all(&sealed_finished).await?;

    let ak = derive_application_keys(
        &hk.handshake_secret,
        &transcript_thru_sfin,
        server_hello_info.suite,
    );

    Ok(RealityStream {
        inner: stream,
        suite: ak.suite,
        client_key: ak.client_key,
        client_iv: ak.client_iv,
        client_seq: 0,
        server_key: ak.server_key,
        server_iv: ak.server_iv,
        server_seq: 0,
        raw_buf: Vec::new(),
        read_buf: Vec::new(),
        read_pos: 0,
        write_buf: Vec::new(),
        write_off: 0,
    })
}

/// An established REALITY/TLS 1.3 connection's application-data stream.
/// Implements `AsyncRead`/`AsyncWrite` over the negotiated application
/// traffic keys, framing plaintext into/out of TLS 1.3 records
/// (RFC 8446 §5.2) with independent per-direction sequence counters. Key
/// update (RFC 8446 §4.6.3) is not implemented — out of scope for the MVP;
/// a long-lived stream that exhausts its 64-bit sequence counter fails
/// closed rather than reusing a nonce.
pub struct RealityStream<S> {
    inner: S,
    /// The negotiated TLS 1.3 cipher suite (`0x1301`/`0x1302`/`0x1303`) —
    /// needed on every seal/open, since `TLS_AES_256_GCM_SHA384` and
    /// `TLS_CHACHA20_POLY1305_SHA256` share a 32-byte key length and so
    /// cannot be told apart from `client_key`/`server_key` alone.
    suite: u16,
    client_key: Vec<u8>,
    client_iv: [u8; 12],
    client_seq: u64,
    server_key: Vec<u8>,
    server_iv: [u8; 12],
    server_seq: u64,
    /// Raw bytes read from `inner` that have not yet been assembled into a
    /// complete TLS record.
    raw_buf: Vec<u8>,
    /// Decrypted application-data plaintext not yet returned to the
    /// `AsyncRead` caller.
    read_buf: Vec<u8>,
    read_pos: usize,
    /// A fully-sealed outgoing record not yet fully written to `inner`.
    write_buf: Vec<u8>,
    write_off: usize,
}

fn protocol_io_error(msg: &'static str) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, msg)
}

fn protocol_io_error_owned(msg: String) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, msg)
}

fn handshake_io_error(e: handshake::Error) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, e.to_string())
}

impl<S: AsyncRead + AsyncWrite + Unpin> RealityStream<S> {
    /// Attempts to decrypt and buffer one more application-data record into
    /// `self.read_buf`, transparently skipping `ChangeCipherSpec` records and
    /// post-handshake handshake-typed records (e.g. `NewSessionTicket`)
    /// interleaved with application data. Returns `Ready(Ok(()))` once at
    /// least one byte of application data has been buffered (or the peer
    /// cleanly closed, in which case `read_buf` is left unchanged and a
    /// subsequent `poll_read` call reports EOF via `Ok(())` with `buf`
    /// untouched).
    fn poll_fill_read_buf(&mut self, cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        loop {
            while self.raw_buf.len() >= RECORD_HEADER_LEN {
                let len = usize::from(u16::from_be_bytes([self.raw_buf[3], self.raw_buf[4]]));
                let total = RECORD_HEADER_LEN + len;
                if self.raw_buf.len() < total {
                    break;
                }
                let record_type = self.raw_buf[0];
                let mut payload = self.raw_buf[RECORD_HEADER_LEN..total].to_vec();
                self.raw_buf.drain(..total);

                if record_type == CONTENT_TYPE_CHANGE_CIPHER_SPEC {
                    continue;
                }
                if record_type != CONTENT_TYPE_APPLICATION_DATA {
                    return Poll::Ready(Err(protocol_io_error(
                        "unexpected outer record type in application-data stream",
                    )));
                }

                let (inner_type, content) = record_open_typed(
                    &self.server_key,
                    &self.server_iv,
                    self.server_seq,
                    self.suite,
                    record_type,
                    &mut payload,
                )
                .map_err(handshake_io_error)?;
                self.server_seq = self.server_seq.checked_add(1).ok_or_else(|| {
                    protocol_io_error("server application sequence counter overflow")
                })?;

                if inner_type == CONTENT_TYPE_APPLICATION_DATA {
                    self.read_buf.extend_from_slice(&content);
                    return Poll::Ready(Ok(()));
                }
                if inner_type == CONTENT_TYPE_ALERT {
                    // RFC 8446 §5.2/§6.1: post-handshake alerts arrive
                    // encrypted, inside TLSInnerPlaintext, exactly like
                    // handshake/application-data content — never as a
                    // distinct outer record type. `content` is
                    // `level(1) || description(1)`.
                    let description = content.get(1).copied();
                    return Poll::Ready(match description {
                        Some(ALERT_DESCRIPTION_CLOSE_NOTIFY) => Ok(()), // clean EOF
                        Some(d) => Err(protocol_io_error_owned(format!(
                            "peer sent a fatal TLS alert (description {d}) instead of application data"
                        ))),
                        None => Err(protocol_io_error("peer sent a truncated TLS alert record")),
                    });
                }
                // Inner type is handshake (e.g. a post-handshake
                // NewSessionTicket) — consumed and ignored, look for the
                // next already-buffered record.
            }

            let mut tmp = [0u8; 4096];
            let mut read_buf = ReadBuf::new(&mut tmp);
            match Pin::new(&mut self.inner).poll_read(cx, &mut read_buf) {
                Poll::Ready(Ok(())) => {
                    let n = read_buf.filled().len();
                    if n == 0 {
                        if self.raw_buf.is_empty() {
                            // Clean EOF at a record boundary.
                            return Poll::Ready(Ok(()));
                        }
                        return Poll::Ready(Err(io::Error::new(
                            io::ErrorKind::UnexpectedEof,
                            "peer closed mid-record",
                        )));
                    }
                    self.raw_buf.extend_from_slice(read_buf.filled());
                }
                Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
                Poll::Pending => return Poll::Pending,
            }
        }
    }
}

impl<S: AsyncRead + AsyncWrite + Unpin> AsyncRead for RealityStream<S> {
    fn poll_read(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &mut ReadBuf<'_>,
    ) -> Poll<io::Result<()>> {
        let this = self.get_mut();
        loop {
            if this.read_pos < this.read_buf.len() {
                let available = this.read_buf.len() - this.read_pos;
                let n = available.min(buf.remaining());
                buf.put_slice(&this.read_buf[this.read_pos..this.read_pos + n]);
                this.read_pos += n;
                if this.read_pos == this.read_buf.len() {
                    this.read_buf.clear();
                    this.read_pos = 0;
                }
                return Poll::Ready(Ok(()));
            }

            let before = this.read_buf.len();
            match this.poll_fill_read_buf(cx) {
                Poll::Ready(Ok(())) => {
                    if this.read_buf.len() == before {
                        // Clean EOF: no new data was buffered.
                        return Poll::Ready(Ok(()));
                    }
                    // New application data buffered; loop to copy it out.
                }
                Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
                Poll::Pending => return Poll::Pending,
            }
        }
    }
}

impl<S: AsyncRead + AsyncWrite + Unpin> AsyncWrite for RealityStream<S> {
    fn poll_write(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
        buf: &[u8],
    ) -> Poll<io::Result<usize>> {
        let this = self.get_mut();

        // Drain any previously sealed-but-unsent record before accepting
        // more application-level bytes, to preserve wire ordering.
        while this.write_off < this.write_buf.len() {
            match Pin::new(&mut this.inner).poll_write(cx, &this.write_buf[this.write_off..]) {
                Poll::Ready(Ok(0)) => {
                    return Poll::Ready(Err(io::Error::new(
                        io::ErrorKind::WriteZero,
                        "write zero",
                    )));
                }
                Poll::Ready(Ok(n)) => this.write_off += n,
                Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
                Poll::Pending => return Poll::Pending,
            }
        }

        if buf.is_empty() {
            return Poll::Ready(Ok(0));
        }

        let chunk_len = buf.len().min(MAX_APP_RECORD_LEN);
        let chunk = &buf[..chunk_len];
        let sealed = record_seal(
            &this.client_key,
            &this.client_iv,
            this.client_seq,
            this.suite,
            CONTENT_TYPE_APPLICATION_DATA,
            chunk,
        )
        .map_err(handshake_io_error)?;
        this.client_seq = this
            .client_seq
            .checked_add(1)
            .ok_or_else(|| protocol_io_error("client application sequence counter overflow"))?;
        let header = record_header(
            CONTENT_TYPE_APPLICATION_DATA,
            LEGACY_RECORD_VERSION,
            sealed.len(),
        )
        .map_err(|e| io::Error::new(io::ErrorKind::InvalidInput, e.to_string()))?;

        let mut record = Vec::with_capacity(RECORD_HEADER_LEN + sealed.len());
        record.extend_from_slice(&header);
        record.extend_from_slice(&sealed);
        this.write_buf = record;
        this.write_off = 0;

        while this.write_off < this.write_buf.len() {
            match Pin::new(&mut this.inner).poll_write(cx, &this.write_buf[this.write_off..]) {
                Poll::Ready(Ok(0)) => {
                    return Poll::Ready(Err(io::Error::new(
                        io::ErrorKind::WriteZero,
                        "write zero",
                    )));
                }
                Poll::Ready(Ok(n)) => this.write_off += n,
                Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
                Poll::Pending => break, // remainder stays buffered for the next poll
            }
        }

        Poll::Ready(Ok(chunk_len))
    }

    fn poll_flush(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        let this = self.get_mut();
        while this.write_off < this.write_buf.len() {
            match Pin::new(&mut this.inner).poll_write(cx, &this.write_buf[this.write_off..]) {
                Poll::Ready(Ok(0)) => {
                    return Poll::Ready(Err(io::Error::new(
                        io::ErrorKind::WriteZero,
                        "write zero",
                    )));
                }
                Poll::Ready(Ok(n)) => this.write_off += n,
                Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
                Poll::Pending => return Poll::Pending,
            }
        }
        Pin::new(&mut this.inner).poll_flush(cx)
    }

    fn poll_shutdown(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<io::Result<()>> {
        let this = self.get_mut();
        while this.write_off < this.write_buf.len() {
            match Pin::new(&mut this.inner).poll_write(cx, &this.write_buf[this.write_off..]) {
                Poll::Ready(Ok(0)) => {
                    return Poll::Ready(Err(io::Error::new(
                        io::ErrorKind::WriteZero,
                        "write zero",
                    )));
                }
                Poll::Ready(Ok(n)) => this.write_off += n,
                Poll::Ready(Err(e)) => return Poll::Ready(Err(e)),
                Poll::Pending => return Poll::Pending,
            }
        }
        Pin::new(&mut this.inner).poll_shutdown(cx)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{auth, ja};

    /// Reads exactly one raw TLS record from a test-side stream half,
    /// mirroring what a real TLS server sees on the wire — used to inspect
    /// what `connect` actually sent without decrypting anything.
    async fn read_one_record<S: AsyncRead + Unpin>(stream: &mut S) -> (u8, Vec<u8>) {
        let mut header = [0u8; RECORD_HEADER_LEN];
        stream.read_exact(&mut header).await.unwrap();
        let len = usize::from(u16::from_be_bytes([header[3], header[4]]));
        let mut payload = vec![0u8; len];
        stream.read_exact(&mut payload).await.unwrap();
        (header[0], payload)
    }

    /// Walks a crafted `ClientHello` handshake message (`0x01 ‖ u24 len ‖
    /// body`) far enough to recover `client_random` and the `x25519`
    /// (group `0x001d`) `key_share` entry's public value — everything a
    /// mock TLS 1.3 server needs to compute the ECDHE shared secret and
    /// derive the same handshake keys `connect` derives. Shared by both the
    /// hello-inspection test above and the full mock-server handshake test
    /// below, rather than duplicating the extension walk twice.
    fn client_hello_random_and_x25519(ch_msg: &[u8]) -> ([u8; 32], [u8; 32]) {
        let body = &ch_msg[4..];
        let client_random: [u8; 32] = body[2..34].try_into().unwrap();
        let sid_len = usize::from(body[34]);

        let mut cursor = 35 + sid_len;
        let cs_len = usize::from(u16::from_be_bytes([body[cursor], body[cursor + 1]]));
        cursor += 2 + cs_len;
        let cm_len = usize::from(body[cursor]);
        cursor += 1 + cm_len;
        let ext_total_len = usize::from(u16::from_be_bytes([body[cursor], body[cursor + 1]]));
        cursor += 2;

        let mut i = cursor;
        let ext_end = cursor + ext_total_len;
        let mut eph_pub = None;
        while i < ext_end {
            let ext_type = u16::from_be_bytes([body[i], body[i + 1]]);
            let ext_len = usize::from(u16::from_be_bytes([body[i + 2], body[i + 3]]));
            let ext_body = &body[i + 4..i + 4 + ext_len];
            if ext_type == 51 {
                let ks_len = usize::from(u16::from_be_bytes([ext_body[0], ext_body[1]]));
                let mut j = 2;
                let ks_end = 2 + ks_len;
                while j < ks_end {
                    let group = u16::from_be_bytes([ext_body[j], ext_body[j + 1]]);
                    let data_len =
                        usize::from(u16::from_be_bytes([ext_body[j + 2], ext_body[j + 3]]));
                    let data = &ext_body[j + 4..j + 4 + data_len];
                    if group == GROUP_X25519 {
                        eph_pub = Some(<[u8; 32]>::try_from(data).unwrap());
                    }
                    j += 4 + data_len;
                }
            }
            i += 4 + ext_len;
        }
        (
            client_random,
            eph_pub.expect("crafted hello must carry an x25519 key_share entry"),
        )
    }

    /// `connect` must emit a byte-faithful `hello::craft` ClientHello whose
    /// `legacy_session_id` is the REALITY seal of the *same* `client_random`
    /// carried in the hello itself — the crux of Task 7's "ONE EPHEMERAL
    /// KEY" / "client_random must match" requirements. This test drives
    /// `connect` only as far as the ClientHello it emits (the mock peer
    /// never replies, so `connect` blocks forever on the ServerHello read
    /// after this — we just inspect what was written and drop the future).
    #[tokio::test]
    async fn connect_emits_a_valid_crafted_hello_sealed_with_its_own_client_random() {
        let (client_io, mut server_io) = tokio::io::duplex(64 * 1024);

        let server_reality_priv = [7u8; 32];
        let server_reality_pub = {
            let secret = x25519_dalek::StaticSecret::from(server_reality_priv);
            x25519_dalek::PublicKey::from(&secret).to_bytes()
        };
        let short_id = [1, 2, 3, 4, 5, 6, 7, 8];

        let connect_task = tokio::spawn(async move {
            let _ = connect(client_io, "example.com", &server_reality_pub, short_id).await;
        });

        let (record_type, ch_msg) = read_one_record(&mut server_io).await;
        assert_eq!(
            record_type, CONTENT_TYPE_HANDSHAKE,
            "ClientHello must be sent as a plaintext handshake record"
        );

        // It must parse as a well-formed Chrome-150 ClientHello (reuse the
        // ja module's own parser as an independent structural check).
        assert!(ja::ja3(&ch_msg).is_some(), "not a well-formed ClientHello");
        assert!(ja::ja4(&ch_msg).is_some(), "not a well-formed ClientHello");

        // Recover client_random and the x25519 key_share pub (shared walk,
        // see `client_hello_random_and_x25519`'s doc comment), plus the
        // legacy_session_id (u8-length-prefixed, right after
        // client_random) — then verify the seal opens under the server's
        // REALITY key with this exact client_random and eph pub, proving
        // hello::craft's wire client_random and auth::seal's sealed
        // client_random are the same value.
        let body = &ch_msg[4..];
        let sid_len = usize::from(body[34]);
        let session_id = &body[35..35 + sid_len];
        assert_eq!(sid_len, 32);

        let (client_random, eph_pub) = client_hello_random_and_x25519(&ch_msg);

        assert!(
            auth::open(
                &server_reality_priv,
                &eph_pub,
                &client_random,
                session_id,
                &[short_id],
                // ts_min "now" — connect() sealed with the current minute.
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_secs()
                    / 60,
                1,
            ),
            "connect's ClientHello legacy_session_id must be a REALITY seal of \
             the SAME client_random carried in the hello, over the SAME \
             ephemeral key as the hello's key_share"
        );

        drop(server_io);
        connect_task.abort();
    }

    /// A hermetic loopback proving `RealityStream`'s `AsyncRead`/`AsyncWrite`
    /// framing round-trips over an arbitrary pair of fixed application
    /// traffic keys, independent of the handshake that produces them —
    /// exercising record chunking/reassembly without needing a live TLS 1.3
    /// peer (full live round-trip is Task 8).
    #[tokio::test]
    async fn reality_stream_round_trips_over_duplex() {
        let (a_io, b_io) = tokio::io::duplex(1 << 20);

        // Symmetric key sets: what A calls "client" is what B calls
        // "server" and vice versa, so each side decrypts what the other
        // encrypts.
        let key_a = vec![0x11u8; 16];
        let iv_a = [0x22u8; 12];
        let key_b = vec![0x33u8; 16];
        let iv_b = [0x44u8; 12];

        let mut a = RealityStream {
            inner: a_io,
            suite: 0x1301, // TLS_AES_128_GCM_SHA256 -- matches the 16-byte test keys
            client_key: key_a.clone(),
            client_iv: iv_a,
            client_seq: 0,
            server_key: key_b.clone(),
            server_iv: iv_b,
            server_seq: 0,
            raw_buf: Vec::new(),
            read_buf: Vec::new(),
            read_pos: 0,
            write_buf: Vec::new(),
            write_off: 0,
        };
        let mut b = RealityStream {
            inner: b_io,
            suite: 0x1301, // TLS_AES_128_GCM_SHA256 -- matches the 16-byte test keys
            client_key: key_b,
            client_iv: iv_b,
            client_seq: 0,
            server_key: key_a,
            server_iv: iv_a,
            server_seq: 0,
            raw_buf: Vec::new(),
            read_buf: Vec::new(),
            read_pos: 0,
            write_buf: Vec::new(),
            write_off: 0,
        };

        a.write_all(b"hello from A").await.unwrap();
        a.flush().await.unwrap();
        let mut buf = vec![0u8; 32];
        let n = b.read(&mut buf).await.unwrap();
        assert_eq!(&buf[..n], b"hello from A");

        b.write_all(b"hi back from B").await.unwrap();
        b.flush().await.unwrap();
        let mut buf2 = vec![0u8; 32];
        let n2 = a.read(&mut buf2).await.unwrap();
        assert_eq!(&buf2[..n2], b"hi back from B");
    }

    /// Plays the TLS 1.3 SERVER role, entirely in-process, against a real
    /// `connect()` call driving the CLIENT role over the other half of a
    /// `tokio::io::duplex` — proving `connect`/`RealityStream` end-to-end
    /// OFFLINE (no real network), using this crate's OWN handshake
    /// primitives on both sides, mirroring exactly what `connect` itself
    /// does but in reverse.
    ///
    /// Always negotiates group `x25519` (`0x001d`), never the ML-KEM hybrid
    /// (`4588`) — `connect` offers both, but a server is free to pick either
    /// per RFC 8446 §4.2.8, and implementing a from-scratch ML-KEM
    /// encapsulation here would duplicate the `ml_kem` crate's job with no
    /// additional coverage of `connect`'s own logic (the `ecdhe` derivation
    /// branch for group 4588 is exercised directly against RFC-vector-shaped
    /// hybrid IKM in `handshake.rs`'s
    /// `derive_handshake_keys_accepts_64_byte_hybrid_ecdhe`).
    ///
    /// Does not send a `Certificate`/`CertificateVerify` — `connect` never
    /// looks at either (see this module's doc comment: REALITY is
    /// zero-cert-auth by design) — and sends an arbitrary (unverified)
    /// server `Finished` `verify_data`, since `connect` consumes but never
    /// validates the server `Finished` contents.
    async fn run_mock_tls13_server(mut io: tokio::io::DuplexStream) {
        const SUITE: u16 = 0x1301; // TLS_AES_128_GCM_SHA256

        // -- ClientHello ------------------------------------------------
        let (record_type, ch_msg) = read_one_record(&mut io).await;
        assert_eq!(
            record_type, CONTENT_TYPE_HANDSHAKE,
            "ClientHello must arrive as a plaintext handshake record"
        );
        let (_client_random, client_x25519_pub) = client_hello_random_and_x25519(&ch_msg);

        // -- ServerHello (group x25519) -----------------------------------
        let server_secret = x25519_dalek::StaticSecret::from([9u8; 32]);
        let server_x25519_pub: [u8; 32] = x25519_dalek::PublicKey::from(&server_secret).to_bytes();
        let ecdhe: Vec<u8> = server_secret
            .diffie_hellman(&x25519_dalek::PublicKey::from(client_x25519_pub))
            .to_bytes()
            .to_vec();

        let mut server_random = [0u8; 32];
        getrandom::getrandom(&mut server_random).unwrap();

        let mut key_share_entry = Vec::new();
        key_share_entry.extend_from_slice(&GROUP_X25519.to_be_bytes());
        key_share_entry.extend_from_slice(&32u16.to_be_bytes());
        key_share_entry.extend_from_slice(&server_x25519_pub);

        let mut exts = Vec::new();
        // supported_versions (43): TLS 1.3 only.
        exts.extend_from_slice(&43u16.to_be_bytes());
        exts.extend_from_slice(&2u16.to_be_bytes());
        exts.extend_from_slice(&0x0304u16.to_be_bytes());
        // key_share (51).
        exts.extend_from_slice(&51u16.to_be_bytes());
        exts.extend_from_slice(&u16::try_from(key_share_entry.len()).unwrap().to_be_bytes());
        exts.extend_from_slice(&key_share_entry);

        let mut sh_body = Vec::new();
        sh_body.extend_from_slice(&0x0303u16.to_be_bytes()); // legacy_version
        sh_body.extend_from_slice(&server_random);
        sh_body.push(0); // legacy_session_id_echo: empty (connect() ignores it)
        sh_body.extend_from_slice(&SUITE.to_be_bytes());
        sh_body.push(0); // legacy_compression_method
        sh_body.extend_from_slice(&u16::try_from(exts.len()).unwrap().to_be_bytes());
        sh_body.extend_from_slice(&exts);

        let mut sh_msg = Vec::new();
        sh_msg.push(0x02); // ServerHello
        let body_len = u32::try_from(sh_body.len()).unwrap().to_be_bytes();
        sh_msg.extend_from_slice(&body_len[1..]); // u24
        sh_msg.extend_from_slice(&sh_body);

        let sh_header =
            record_header(CONTENT_TYPE_HANDSHAKE, LEGACY_RECORD_VERSION, sh_msg.len()).unwrap();
        io.write_all(&sh_header).await.unwrap();
        io.write_all(&sh_msg).await.unwrap();

        // -- Handshake keys, matching connect()'s own derivation exactly --
        let mut ch_sh_transcript = Vec::with_capacity(ch_msg.len() + sh_msg.len());
        ch_sh_transcript.extend_from_slice(&ch_msg);
        ch_sh_transcript.extend_from_slice(&sh_msg);
        let transcript_ch_sh = transcript_hash(&ch_sh_transcript, SUITE);
        let hk = derive_handshake_keys(&ecdhe, &transcript_ch_sh, SUITE);

        // -- Middlebox-compatibility CCS, then the encrypted server flight:
        // EncryptedExtensions(empty) ‖ Finished(arbitrary verify_data) ------
        io.write_all(&CHANGE_CIPHER_SPEC_RECORD).await.unwrap();

        let ee_msg: [u8; 4] = [0x08, 0x00, 0x00, 0x00]; // EncryptedExtensions, 0-length
        let verify_data = [0xABu8; 32]; // arbitrary: connect() never checks it
        let mut finished_msg = Vec::with_capacity(4 + verify_data.len());
        finished_msg.push(HS_TYPE_FINISHED);
        finished_msg.extend_from_slice(&[0x00, 0x00, 0x20]); // u24 len = 32
        finished_msg.extend_from_slice(&verify_data);

        let mut server_flight_plain = Vec::with_capacity(ee_msg.len() + finished_msg.len());
        server_flight_plain.extend_from_slice(&ee_msg);
        server_flight_plain.extend_from_slice(&finished_msg);

        let sealed_flight = record_seal(
            &hk.server_key,
            &hk.server_iv,
            0,
            SUITE,
            CONTENT_TYPE_HANDSHAKE,
            &server_flight_plain,
        )
        .unwrap();
        let flight_header = record_header(
            CONTENT_TYPE_APPLICATION_DATA,
            LEGACY_RECORD_VERSION,
            sealed_flight.len(),
        )
        .unwrap();
        io.write_all(&flight_header).await.unwrap();
        io.write_all(&sealed_flight).await.unwrap();

        let mut full_transcript = ch_sh_transcript;
        full_transcript.extend_from_slice(&server_flight_plain);
        let transcript_thru_sfin = transcript_hash(&full_transcript, SUITE);
        let ak = derive_application_keys(&hk.handshake_secret, &transcript_thru_sfin, SUITE);

        // -- Drain the client's CCS + sealed Finished (contents unchecked,
        // exactly mirroring connect()'s own "never verifies the peer's
        // Finished" stance) ------------------------------------------------
        loop {
            let (record_type, _payload) = read_one_record(&mut io).await;
            if record_type == CONTENT_TYPE_CHANGE_CIPHER_SPEC {
                continue;
            }
            assert_eq!(
                record_type, CONTENT_TYPE_APPLICATION_DATA,
                "expected the client's sealed Finished record"
            );
            break;
        }

        // -- Echo one application-data record under the application keys --
        let (record_type, mut app_payload) = read_one_record(&mut io).await;
        assert_eq!(record_type, CONTENT_TYPE_APPLICATION_DATA);
        let plaintext = record_open(
            &ak.client_key,
            &ak.client_iv,
            0,
            SUITE,
            CONTENT_TYPE_APPLICATION_DATA,
            &mut app_payload,
        )
        .unwrap();

        let sealed_reply = record_seal(
            &ak.server_key,
            &ak.server_iv,
            0,
            SUITE,
            CONTENT_TYPE_APPLICATION_DATA,
            &plaintext,
        )
        .unwrap();
        let reply_header = record_header(
            CONTENT_TYPE_APPLICATION_DATA,
            LEGACY_RECORD_VERSION,
            sealed_reply.len(),
        )
        .unwrap();
        io.write_all(&reply_header).await.unwrap();
        io.write_all(&sealed_reply).await.unwrap();
    }

    /// The end-to-end, fully OFFLINE proof: `connect()` (the CLIENT role)
    /// against `run_mock_tls13_server` (the SERVER role, built from this
    /// same crate's `handshake` primitives) over an in-process
    /// `tokio::io::duplex` — no real network, no `#[ignore]`. Drives
    /// `connect` all the way through `ClientHello` → `ServerHello` → key
    /// derivation → server flight → client `Finished` → application data,
    /// then round-trips one message over the resulting `RealityStream`,
    /// exercising the `AsyncRead`/`AsyncWrite` impls with data actually
    /// produced by a full handshake (as opposed to
    /// `reality_stream_round_trips_over_duplex`'s hand-picked fixed keys).
    #[tokio::test]
    async fn connect_completes_full_handshake_against_in_process_mock_server() {
        let (client_io, server_io) = tokio::io::duplex(64 * 1024);

        let server_task = tokio::spawn(run_mock_tls13_server(server_io));

        let mut s = connect(client_io, "example.com", &[9u8; 32], [1u8; 8])
            .await
            .expect("handshake against the in-process mock server must succeed");

        s.write_all(b"PING").await.unwrap();
        s.flush().await.unwrap();

        let mut buf = [0u8; 4];
        s.read_exact(&mut buf).await.unwrap();
        assert_eq!(&buf, b"PING");

        server_task.await.unwrap();
    }
}
